app_roma/urls.py
from django.urls import path, include
from .views import Index, CourseList, teacher_list, StartGroup, start_work, EduProcces, About, error, robot, pdf_response
app_name = 'app_roma'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('list_courses/', CourseList.as_view(), name='list_courses'),
    path('teachers/', teacher_list, name='teachers'),
    path('near_groups/', StartGroup.as_view(), name='near_groups'),
    path('start_work/', start_work, name='start_work'),
    path('educ/', EduProcces.as_view(), name='edu_procces'),
    path('about/', About.as_view(), name='about'),
    path('error/', error, name='error'),
    path('robots.txt/', robot),
    # path('pdf/', pdf_response, name='pdf_response')
    path('course_program/<int:id>', pdf_response, name='pdf_response'),
]

develop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_roma.urls'))
]

templates/about__itec.html
{% extends 'main.html' %}
{% load static %}

    {% block title %}
    <title>
        Школа ITEC. Обучение программированию, верстке сайтов и английский для программистов.
    </title>
    <meta name="description" content="Школа ITEC - профессиональное обучение программированию, программирование серверов, создание БД.">
    <meta name="keywords" content="Английский для программистов, верстка сайтов, программирование сервера, создание БД">
    {% endblock %}

    {% block css %}
    <link rel="icon" href="{% static 'img/about__itec_white.svg' %}">
    <link rel="stylesheet" href="{% static 'css/menu_for_about_itec.css' %}">
    <link rel="stylesheet" href="{% static 'css/about__itec.css' %}">
    {% endblock %}


    {% block content %}
    <div class="about-itec" id="content">
        <h1 class="about-itec__title">
            Что такое ITEC?
        </h1>
        <div class="about-itec__subtitle">
            Онлайн тур
        </div>
        <div class="about-itec__subsubtitle">
            Находимся в центре Минска. Современные аудитории с видом <span>на Национальный олимпийский стадион «Динамо»</span>
        </div>
        <div id="slider-block" class="about-itec__online-tour">
            <div class="online-tour__arrow-wrapper-right">
                <div class="arrow__right">

                </div>
            </div>
            <div class="online-tour__arrow-wrapper-left">
                <div class="arrow__left">

                </div>
            </div>
            <div class="about-itec__online-tour-wrapper">
                <div id="chec_point_1" class="about-itec__online-tour-circle">

                </div>
                <div id="chec_point_2" class="about-itec__online-tour-circle">
                    
                </div>
                <div id="chec_point_3" class="about-itec__online-tour-circle">
                    
                </div>
                <div id="chec_point_4" class="about-itec__online-tour-circle">
                    
                </div>
                <div id="chec_point_5" class="about-itec__online-tour-circle">
                    
                </div>
                <div id="chec_point_6" class="about-itec__online-tour-circle">
                    
                </div>
            </div>
        </div>
        <div class="about-itec__advantages">
            <div class="advantages">
                <h2 class="advantages__title">
                    Наша основная задача:
                </h2>
                <div class="advantages__text">
                    Современные технологии стремительно развиваются каждый день, и главная цель каждого успешного человека — саморазвитие и решение поставленных задач. Предлагаем достичь этой цели вместе с нами! Мы не дадим «сухой» информации о том, как что-то делается сейчас, мы откроем Вам секрет, как научиться делать это самому!
                </div>
                <div class="advantages__text">
                    Самое интересное, что мы вывели из многолетней практики преподавания — это то, что человек имеет свободную волю, а главное – собственный выбор, за который он, и только он персонально несет ответственность, как перед собой, так и перед средой его жизнедеятельности. Если вы сделали осознанный выбор и хотите стать профессионалом, то приходите к нам - мы поможем.
                </div>
            </div>
            <div class="advantages">
                <h2 class="advantages__title">
                    Наши преимущества:
                </h2>
                <div class="advantages__text">
                    Мы не привлекаем Вас высокими зарплатами со старта, а помогаем Вам полюбить новое дело и добиться успеха в нем
                </div>
                <div class="advantages__text">
                    Основная задача нашей школы — дать обучающимся качественную базу знаний, которая поможет им стать профессионалами. Уверены, что такой подход к обучению - самый верный путь к успешной карьере в IT
                </div>
                <div class="advantages__text">
                    Лучшие выпускники получат возможность попасть в программу StartWork и принять участие в разработке оплачиваемого проекта и возможность дальнейшего партнерства с нами.
                </div>
                <div class="advantages__text">
                    Мы имеем возможность и необходимые инструменты для подготовки соискателей до трудоустройства в компанию его мечты.
                </div>
            </div>
        </div>
        <div class="about-itec__advantages">
            <div class="advantages">
                <h2 class="advantages__title">
                    Начиная с 2012 года мы:
                </h2>
                <div class="advantages__text">
                    Провели множество курсов, семинаров, мероприятий по разработке ПО, системному и бизнес-анализу, архитектуре ПО, wеb -разработке, разработке мобильных и wеb-приложений и другим направлениям в IT-сфере, и сейчас наша команда обладает уникальным опытом по обучению этим направлениям с нуля.
                </div>
            </div>
            <div class="advantages">
                <h2 class="advantages__title">
                    Дружный коллектив:
                </h2>
                <div class="advantages__text">
                    У нас Вы можете познакомиться с интересными людьми. Сходить в сауну или получить скидку на занятие в спортивном зале.
                </div>
            </div>
        </div>
        <div class="about-itec__form-wrapper">
            <div class="form-wrapper__title">
                Хотите стать частью тусовки ITEC?
            </div>
            <div class="form-wrapper__subtitle">
                Запишитесь на консультацию и мы расскажем <span>как это можно сделать.</span>
            </div>
            <form action="{% url 'app_roma:about' %}" method="POST">
                <div class="form">
                    <div class="form__title">
                        Номер телефона
                    </div>
                    {% include 'form.html' %}
                    <button class="form__button">
                        Записаться на консультацию
                    </button>
                    <div class="form__subtitle">
                        Перезвоним в течение 5 минут
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% endblock %}
    {% block script %}
    <script src="{% static 'js/slider_event.js' %}"></script>
    {% endblock %}

templates/course_page.html
{% extends 'main.html' %}
{% load static %}

    {% block title %}
    <title>Стать программистом за 5 месяцев | Выбери свое направление | Фронтенд, бэкенд или фулстек-разработчик</title>
    {% endblock %}

    {% block meta %}
    <meta name="description" content="Как стать программистом за 5 месяцев с последуюшим трудоустройством | Выбери свое направление | Фронтенд, бэкенд или фулстек-разработка">
    <meta name="keywords" content="Фронтенд разработчик, бэкэнд разработчик, фулстэк разработчик, стать программистом, обучение с трудоустройством">
    {% endblock %}

    {% block css %}
    <link rel="icon" href="{% static 'img/course_catalog_white.svg' %}">
    <link rel="stylesheet" href="{% static 'css/course_page.css' %}">
    <link rel="stylesheet" href="{% static 'css/form__application.css' %}">
    <link rel="stylesheet" href="{% static 'css/menu_for_catalog_course.css' %}">
    {% endblock %}

        {% block content %}
        <div  class="container__course" id="content">
            <h1 class="course__title">
                Каталог курсов
            </h1>
            <div class="course__subtitle">
                «Ничему нельзя научить, всему можно только научиться.»
            </div>
            <div class="course__subtitle">
                К.С. Станиславский
            </div>
            {%  for i in obj %}
            <div class="course__name-wrapper">
                <a name="front">
                    <h2 class="course__name">
                        {{i.name_specialization}}
                    </h2>
                </a>
                <div class="course__number-course">
                    {% if i.spec.all|length == 1  %}
                    {{ i.spec.all|length }} курс
                    {% elif i.spec.all|length <= 4 %}
                    {{ i.spec.all|length }} курса
                    {% else %}
                    {{ i.spec.all|length }} курсов
                    {% endif %}
                </div>
            </div>

            <div class="course__wrapper">
                {% for item in i.spec.all  %}
                <div class="course__about">
                <div class="about__start-text">
                    {% if item.name_courses == 'Node.js, серверная разработка' %}
                    Идет набор в группу
                    {% else %}
                    Старт обучения: <span>{{item.add_course.first.data_begins|date:'j E'}}</span>
                    {% endif %}
                </div>
                <h3 class="about__title">
                    {{item.name_courses }}
                </h3>
                <div class="about__subtitle">
                    {{item.description_course}}
                </div>
                <ul class="about__list">
                    {% for spec in item.course.all %}
                    <li>
                        {{spec.detail}}
                    </li>
                    {% endfor %}
                </ul>
                <div class="about__form">
                    <button type="submit" class="about__form-button">
                        Оставить заявку
                    </button>
                    <div class="about__form-wrapper">
                        <a href="{% url 'app_roma:pdf_response' id=item.id %}" class="about__form-link">
                            Программа обучения
                        </a>
                        <a href="{% url 'app_roma:pdf_response' id=item.id %}" class="about__form-link-specialty">
                            О специальности
                        </a>
                    </div>
                </div>
                <div class="about__wrapper">
                    <div class="about__training">
                        <div class="training__time">
                            {% if item.quantity_lesson == 1 %}
                            {{item.quantity_lesson}} месяц
                            {% elif item.quantity_lesson <= 4 %}
                            {{item.quantity_lesson}} месяца
                            {% else %}
                            {{item.quantity_lesson}} месяцев
                            {% endif %}
                        </div>
                        <div class="training__text">
                            Время обучения
                        </div>
                    </div>
                    <div class="about__cost">
                        <div class="cost__text">
                            {{ item.cross_cost}} BYN
                        </div>
                        <div class="cost__number">
                            {{item.cost|floatformat:"0"}} BYN
                        </div>
                        <div class="cost__text">
                            Стоимость в месяц {{ item.cost_in_month }} BYN
                        </div>
                    </div>
                </div>
                <div class="about__line">

                </div>
                <div class="about__bottom">
                    <div class="bottom__text">
                        Курс — Английский в IT
                    </div>
                    <div class="bottom__text">
                        Скидка 40%
                    </div>
                    <div class="bottom__text">
                        Выгода 70 BYN
                    </div>
                </div>
                </div>

                {% endfor %}
            </div>
            {% endfor %}
            
            <div class="course__container-english">
                <div class="course__english-wrapper">
                    <div class="course__english">
                        <h2 class="english__title">
                            Английский для IT
                        </h2>
                        <div class="english__subtitle">
                            Делаем упор на стек технологий, которые вы изучаете
                        </div>
                        <div class="english__subtitle">
                            В живых диалогах закрепляем фразы, которые пригодятся в работе, на собеседованиях и переговорах!
                        </div>
                        <div class="english__wrapper-subtitle">
                            <div class="english__subtitle english__subtitle-margin">
                                <span>4 месяца</span> Время обучения
                            </div>
                            <div class="english__subtitle">
                                <span>{{eng.price}} BYN</span>Стоимость курса
                            </div>
                        </div>
                    </div>
                    <div class="english__about-line">
                        <img src="{% static 'img/course_line.svg' %}" alt="" class="english__about-line-img">
                    </div>
                    <div class="course__english-about">
                        <div class="english__about-text">
                            Комплексная программа изучения английского языка 
                            для специалистов IT-сферы. Направлена на формирование и дальнейшее совершенствование речевых навыков в профессиональной среде.
                        </div>
                        <div class="english__about-text">
                            Английский нужен для понимания терминологии, работы 
                            с англоязычными интерфейсами, чтения технической документации, изучения профессиональной литературы и т.д.
                        </div>
                    </div>
                </div>
                <div class="english__wrapper">
                    <button type="submit" class="english__button">
                        Оставить заявку
                    </button>
                    <div class="english__cost ">

                        <div>{{eng.price_in_month}} BYN</div>
                        <div class="english__subtitle"> Цена в месяц </div>
                    </div>
                    <div class="english__discount-circle">
                        <div class="discount__circle">
                            <div class="circle__text">
                                Скидка
                            </div>
                            <div class="circle__text">
                                40%
                            </div>
                        </div>
                    </div>
                    <div class="english__text-wrapper">
                        <div class="english__text">
                            При покупке
                        </div>
                        <div class="english__text">
                            любого курса
                        </div>
                    </div>
                </div>
            </div>
            <div class="course__title-question">
                Есть вопрос о специальностях?
            </div>
            <div class="course__subtitle-question">
                Расскажем про все особенности курсов. <span>Ответим на вопросы</span>
            </div>
            <form action="{% url 'app_roma:list_courses' %}" class="course__form" method="POST">
                <div class="form">
                    <div class="course__form-text">
                        Номер телефона
                    </div>
                    {% include 'form.html' %}

                    <button class="course__form-button">
                        Получить консультацию
                    </button>
                    <div class="course__form-text">
                        Перезвоним в течение 5 минут
                    </div>
                </div>
            </form>
        </div>
        <div class="container__form-application" id="form_app">
            <div class="form-application__block">
                <div class="form-application__cross">
                    <img src="{% static 'img/cross.svg' %}" alt="" class="form-application__cross-img">
                </div>
                <div class="form-application__image">
                    <img src="{% static 'img/form__image-application.svg' %}" alt="" class="form-application__img">
                </div>
                <div class="form-application__text-wrapper">
                    <div class="form-application__text">
                        Заявка на курс
                    </div>
                    <div class="form-application__name-course">
                        "Название курса"
                    </div>
                </div>
                <form action="{% url 'app_roma:list_courses' %}" method="POST">
                    {% include 'form_course.html' %}

                    <div class="form-application__form-wrapper">
                        <button class="form-application__button">
                            Оставить заявку
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% endblock %}

    {% block script %}
    <script src="{% static 'js/form_application_for_catalog_course.js' %}"></script>
    {%  endblock %}

templates/education_process.html
{% extends 'main.html' %}
{% load static %}
    {% block title %}
    <title>Уникальная  методика обучения программированию.</title>
    {% endblock %}
    {% block meta%}
    <meta name="description" content="Обучение программированию офлайн | Онлайн занятия по программированию | Видеокурсы | Пройденный материал в круглосуточном доступе">
    <meta name="keywords" content="Курсы программирования, программирование онлайн, обучение HTML, курс javascript, курс Python">
    {% endblock %}
    {% block css %}
    <link rel="icon" href="{% static 'img/education__white.svg' %}">
    <link rel="stylesheet" href="{% static 'css/menu_for_education_process.css' %}">
    <link rel="stylesheet" href="{% static 'css/education_process.css' %}">
    {% endblock %}

    {% block content %}
        <div class="education" id="content">
            <h1 class="education__title">
                Как проходит обучение и что Вас ждёт после? 
            </h1>
            <iframe width="1100" height="500" src="https://www.youtube.com/embed/hHB3khb86OE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
            </iframe>
            <div class="education__wrapper">
                <div class="education__platform">
                    <div class="platform__title">
                        Своя обучающая платформа
                    </div>
                    <div class="platform__text">
                        Нашей командой разработана обучающая платформа, которая делает процесс обучения проще и эффективнее. Доступ к ней получают все студенты.
                    </div>
                    <div class="platform__text">
                        На протяжении всего обучения формируется <span>личная карточка</span> с оценками и достижениями. Эти данные станут отличным <span>резюме для HR-специалистов</span>, а также портфолио на фрилансе.
                    </div>
                </div>
                <div class="education__platform">
                    <div class="platform__title">
                        Особенности платформы:
                    </div>
                    <ul class="platform__list">
                        <li class="platform__item">
                            Вся необходимая информация хранится в одном месте — учебные материалы, записи уроков, домашняя работа и многое другое.
                        </li>
                        <li class="platform__item">
                            Связь с преподавателями и менеджерами.
                        </li>
                        <li class="platform__item">
                            Чат группы.
                        </li>
                    </ul>
                </div>
            </div>
            <h2 class="education__title">
                Формат обучения выбираете сами
            </h2>
            <div class="education__format">
                <div class="format">
                    <div class="format__link offline red_format">
                        Офлайн
                    </div>
                    <div class="format__link online">
                        Онлайн в <span>разработке</span>
                    </div>
                    <div  class="format__link videocourse">
                        Видеокурс в <span>разработке</span>
                    </div>
                </div>
                <div class="format__line">

                </div>
                <div class="format__about">
                    <div class="format__online"  >
                        <div class="about__wrapper">
                            <div class="about__title">
                                Запись занятий
                            </div>
                            <div class="about__text">
                                Всем студентам данного формата обучения будет предоставлен постоянный доступ к видеозаписям всех прошедших занятий. Это позволит лучше разобраться в упущенных моментах или освежить знания.
                            </div>
                        </div>
                        <div class="about__wrapper">
                            <div class="about__title">
                                Экономия времени
                            </div>
                            <div class="about__text">
                                Не нужно и в снег, и в зной бежать из дома или с работы, стоять в пробках или ехать в душном транспорте для того, чтобы не опоздать на занятие.
                            </div>
                        </div>
                        <div class="about__wrapper">
                            <div class="about__title">
                                Географическая свобода
                            </div>
                            <div class="about__text">
                                Другой город? Другая страна? Для онлайн-обучения это не имеет значения. Вам понадобится только ПК (телефон) и доступ в интернет.
                            </div>
                        </div>
                    </div>
                    <div class="format__offline">
                        <div class="about__wrapper">
                            <div class="about__title title__offline">
                                Живое общение
                            </div>
                            <div class="about__text">
                                Непосредственное общение с наставником позволяет на месте обсудить вопросы, получить обратную связь, попросить совета. Преподаватель поддержит, укажет на сложные моменты, а также посоветует, что сделать, чтобы восполнить пробелы в знаниях.
                            </div>
                        </div>
                        <div class="about__wrapper">
                            <div class="about__title title__offline">
                                Мотивация
                            </div>
                            <div class="about__text">
                                Новые знания усваиваются намного быстрее и эффективнее, когда студенты взаимодействует друг с другом. Также нельзя прийти на занятие неподготовленным, необходимо вовремя и в полном объеме выполнять указания преподавателя, чтобы не отставать от группы. Здоровая конкуренция повышает общую успеваемость. 
                            </div>
                        </div>
                        <div class="about__wrapper">
                            <div class="about__title title__offline">
                                Networking
                            </div>
                            <div class="about__text">
                                Офлайн-курсы — это еще и новые знакомства. А совместная реализация жизнеспособного проекта — первый шаг на пути развития своего бизнеса или карьеры.
                            </div>
                        </div>
                    </div>
                    <div class="format__videocourse" >
                        <div class="about__wrapper">
                            <div class="about__title">
                                Свободный график
                            </div>
                            <div class="about__text">
                                Для некоторых людей обучение в строго установленное время является невозможным из-за работы или других дел. В этом случае, видеокурсы станут лучшим решением, т.к. учиться можно в любое удобное время.
                            </div>
                        </div>
                        <div class="about__wrapper">
                            <div class="about__title">
                                Постоянный доступ к материалам курса
                            </div>
                            <div class="about__text">
                                Все видео из приобретенного курса доступны в любое время и с любого устройства (ПК, телефон, планшет).
                            </div>
                        </div>
                        <div class="about__wrapper">
                            <div class="about__title">
                                Система «вопрос-ответ»
                            </div>
                            <div class="about__text">
                                Возможность задавать вопросы преподавателю и получать помощь в решении возникших проблем.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="education__form-title">
                Не определились со специальностью?
            </div>
            <div class="education__form-subtitle">
                Запишитесь на бесплатную профориентацию 
            </div>
            <form action="{% url 'app_roma:edu_procces' %}" method="POST">
                <div class="form__wrapper">
                    <div class="education__form">
                        <div class="education__form-text">
                            Номер телефона
                        </div>
                        {% include 'form.html' %}
                        <button class="education__form-button">
                            Записаться на консультацию
                        </button>
                        <div class="education__form-text">
                            Перезвоним в течение 5 минут
                        </div>
                    </div>
                </div>
            </form>
            <div class="education__button-wrapper">
                <a href="{% url 'app_roma:list_courses' %}" class="education__button">
                    Выбрать курс
                </a>
            </div>
        </div>
        {% endblock %}

    {% block script %}
    <script src="{% static 'js/format_education_process.js' %}"></script>
    {% endblock %}

templates/error.html
{% extends 'main.html' %}
{% load static %}

    {% block title %}
    <title>Упс ошибочка</title>
    {% endblock %}

    {% block css %}

    <link rel="stylesheet" href="{% static 'css/menu_for_error.css' %}">
    <link rel="stylesheet" href="{% static 'css/error.css' %}">

    {% endblock %}

    {% block content %}
    <div class="container__error" id="content">
        <div class="error__wrapper">
            <div class="error__image-wrapper">
                <img src="{% static 'img/error_bot.svg' %}" alt="" class="error__image">
            </div>
            <div class="error__text-wrapper">
                <div class="error__title">
                    Упс!
                </div>
                <div class="error__subtitle">
                    Ошибочка вышла. Вот ссылочка <span>на <a href="{% url 'app_roma:index' %}" class="error__link">главную</a>, чтобы не теряться :)</span>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

templates/form.html
{% csrf_token %}
{{form.number_phone}}

templates/form_course.html
{% csrf_token %}
{{form.name}}
{{form.number_phone}}
{{ form.courser }}